spring.application.name=ENOTES-API-SERVICE
spring.datasource.username=root
spring.datasource.password=Jitendra@500
spring.datasource.url=jdbc:mysql://localhost:3306/enotes
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
# Show DML (Data Manipulation Language) SQLs
spring.jpa.show-sql=true

# Format SQL nicely in logs (optional)
spring.jpa.properties.hibernate.format_sql=true


# Show DDL logs by enabling logging level
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=DEBUG

